name: Ravindu Lakmina
title: Cybersecurity Engineer
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      domain: ravindu.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
      url: https:/ravindu.github.io  # the base hostname and protocol for your site, e.g. http://example.com
      

theme: minima
