name: Your Name
title: Cybersecurity Engineer
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty
